name:                haskell-rl
version:             0.1.0.0
github:              "jordanrule/haskell-rl"
license:             BSD3
author:              "Jordan Rule"
maintainer:          "jordanrule@gmail.com"
copyright:           "2022 Jordan Rule"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jordanrule/haskell-rl#readme>

dependencies:
- base
- time
- random

library:
  source-dirs: src

executables:
  chapter-one:
    main:                C1.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-rl

tests:
  haskell-rl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-rl
